<?php
declare(strict_types=1);
$root=dirname(__DIR__);$file=$root.'/data/yangiliklar.json';$notice='';$error='';
$default=['intro'=>'','hero_image'=>'','posts'=>[]];
function readNews(string $file,array $default):array{$raw=is_file($file)?file_get_contents($file):false;$data=is_string($raw)?json_decode($raw,true):null;if(!is_array($data))$data=$default;foreach($default as $k=>$v){if(!array_key_exists($k,$data))$data[$k]=$v;if(is_array($v)&&!is_array($data[$k]))$data[$k]=$v;}return $data;}
function parsePosts(string $raw):array{$items=[];foreach(preg_split('/\R/',$raw)?:[] as $line){$line=trim($line);if($line==='')continue;$item=json_decode($line,true);if(!is_array($item))throw new RuntimeException('Har bir post alohida JSON object bo‘lishi kerak.');$items[]=$item;}return $items;}
function postsToLines(mixed $items):string{$out=[];foreach(is_array($items)?$items:[] as $item){if(!is_array($item))continue;$j=json_encode($item,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($j!==false)$out[]=$j;}return implode("\n",$out);}
function e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$data=readNews($file,$default);
if($_SERVER['REQUEST_METHOD']==='POST'){try{$intro=trim((string)($_POST['intro']??''));$hero=trim((string)($_POST['hero_image']??''));if($hero!==''&&!preg_match('#^(?:https?://|/|\.\./|media/)#i',$hero))throw new RuntimeException('Hero image path xavfsiz formatda emas.');$data=['intro'=>$intro,'hero_image'=>$hero,'posts'=>parsePosts((string)($_POST['posts']??''))];$json=json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($json===false||file_put_contents($file,$json.PHP_EOL,LOCK_EX)===false)throw new RuntimeException('JSON faylini saqlash amalga oshmadi.');$notice='Yangiliklar kontenti saqlandi.';}catch(RuntimeException $ex){$error=$ex->getMessage();}}
?>
<!doctype html><html lang="uz"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Yangiliklar — CHIMYON SCHOOL Admin</title><style>
:root{--bg:#f4f4f1;--paper:#fff;--ink:#101722;--muted:#6b7380;--navy:#14213d;--gold:#b99758;--line:rgba(16,23,34,.1);--shadow:0 30px 90px rgba(20,33,61,.08)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}.shell{width:min(1180px,calc(100% - 40px));margin:auto}.top{height:82px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.brand{font-size:12px;font-weight:850;letter-spacing:.15em}.back{color:var(--ink);text-decoration:none;font-size:12px;font-weight:750}.back:hover{color:var(--gold)}main{padding:72px 0 100px}.heading{display:flex;justify-content:space-between;align-items:end;gap:50px;margin-bottom:56px}.eyebrow{margin:0 0 15px;color:var(--gold);font-size:10px;font-weight:850;letter-spacing:.2em;text-transform:uppercase}.heading h1{margin:0;font-size:clamp(56px,8vw,96px);line-height:.86;letter-spacing:-.075em}.heading p{max-width:390px;margin:0;color:var(--muted);font-size:13px;line-height:1.75}.notice,.error{padding:14px 18px;margin-bottom:22px;background:#fff;border:1px solid var(--line);font-size:13px}.error{color:#8b3f36;border-color:rgba(139,63,54,.18)}.form{background:var(--paper);box-shadow:var(--shadow);padding:44px}.field label{display:block;margin-bottom:9px;font-size:10px;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.field input,.field textarea{width:100%;border:0;border-bottom:1px solid rgba(16,23,34,.16);background:transparent;color:var(--ink);outline:none;padding:13px 0;font:inherit;font-size:15px}.field textarea{min-height:155px;resize:vertical;border:1px solid var(--line);padding:14px;line-height:1.65}.field input:focus,.field textarea:focus{border-color:var(--navy)}.field small{display:block;margin-top:8px;color:var(--muted);font-size:10px;line-height:1.55}.guide{margin:36px 0 20px;padding:20px 0 0;border-top:1px solid var(--line)}.guide strong{display:block;margin-bottom:8px;font-size:13px}.guide p{margin:0;color:var(--muted);font-size:11px;line-height:1.7}.actions{display:flex;align-items:center;justify-content:space-between;gap:24px;padding-top:28px;margin-top:38px;border-top:1px solid var(--line)}.hint{color:var(--muted);font-size:10px;line-height:1.6}.save{border:0;background:var(--navy);color:#fff;padding:15px 24px;cursor:pointer;font:inherit;font-size:11px;font-weight:850;letter-spacing:.06em}.save:hover{background:#1d3154}.footer{margin-top:24px;color:var(--muted);font-size:10px}@media(max-width:720px){.shell{width:min(100% - 26px,600px)}main{padding:48px 0 70px}.heading{display:block}.heading p{margin-top:24px}.form{padding:26px}.actions{align-items:stretch;flex-direction:column}.save{width:100%}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style></head><body><div class="shell"><header class="top"><div class="brand">CHIMYON / ADMIN</div><a class="back" href="index.php">← Control center</a></header><main>
<section class="heading"><div><p class="eyebrow">06 / EDITORIAL</p><h1>Yangiliklar.</h1></div><p>Yangiliklar va voqealarni mavjud JSON modelini saqlagan holda boshqaring. Faqat real, tekshirilgan kontentni e’lon qiling.</p></section>
<?php if($notice):?><div class="notice" role="status"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="error" role="alert"><?=e($error)?></div><?php endif;?>
<form class="form" method="post" autocomplete="off">
<div class="field"><label for="intro">Intro</label><textarea id="intro" name="intro" rows="5"><?=e($data['intro'])?></textarea></div>
<div class="field" style="margin-top:30px"><label for="hero_image">Hero image path</label><input id="hero_image" name="hero_image" value="<?=e($data['hero_image'])?>" placeholder="media/images/..."><small>Faqat mavjud media path yoki ishonchli URL.</small></div>
<div class="guide"><strong>Post records</strong><p>Har bir qator bitta JSON object. Mavjud fieldlar saqlanadi. Uydirma yangilik yoki sana kiritmang.</p></div>
<div class="field"><label for="posts">Posts — JSONL</label><textarea id="posts" name="posts" rows="22" spellcheck="false" placeholder='{"title":"...","date":"...","image":"...","excerpt":"..."}'><?=e(postsToLines($data['posts']))?></textarea><small>Har bir qatorda bitta JSON object. Bo‘sh qoldirilsa <code>[]</code> saqlanadi.</small></div>
<div class="actions"><div class="hint">JSON UTF-8 · pretty-print · LOCK_EX · existing schema preserved · PHP 8.x.</div><button class="save" type="submit">SAVE CHANGES →</button></div></form>
<p class="footer">data/yangiliklar.json · <?=count(is_array($data['posts'])?$data['posts']:[])?> post records · zero dependencies</p></main></div></body></html>
